// Code generated by goctl. DO NOT EDIT.
// Source: interaction.proto

package server

import (
	"context"

	"github.com/sunflower10086/TikTok/interaction/internal/logic"
	"github.com/sunflower10086/TikTok/interaction/internal/svc"
	___interaction "github.com/sunflower10086/TikTok/interaction/pb"
)

type InteractionServer struct {
	svcCtx *svc.ServiceContext
	___interaction.UnimplementedInteractionServer
}

func NewInteractionServer(svcCtx *svc.ServiceContext) *InteractionServer {
	return &InteractionServer{
		svcCtx: svcCtx,
	}
}

func (s *InteractionServer) FavoriteAction(ctx context.Context, in *___interaction.FavoriteActionReq) (*___interaction.Empty, error) {
	l := logic.NewFavoriteActionLogic(ctx, s.svcCtx)
	return l.FavoriteAction(in)
}

func (s *InteractionServer) FavoriteList(ctx context.Context, in *___interaction.FavoriteListReq) (*___interaction.FavoriteListResp, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}

func (s *InteractionServer) CommentAction(ctx context.Context, in *___interaction.CommentActionReq) (*___interaction.CommentActionResp, error) {
	l := logic.NewCommentActionLogic(ctx, s.svcCtx)
	return l.CommentAction(in)
}

func (s *InteractionServer) CommentList(ctx context.Context, in *___interaction.CommentListReq) (*___interaction.CommentListResp, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}
